package midterm;
import simView.*;
import java.awt.*;

public class ef extends ViewableDigraph
{
	
	public ef()
	{
		this("ef", 10, 10);
	}
	
	public ef(String name, double processing_timeOfp_1, double processing_timeOfp_2)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		
		ViewableAtomic p_1 = new proc1("p_1", processing_timeOfp_1);
		ViewableAtomic p_2 = new proc2("p_2", processing_timeOfp_2);

		add(p_1);
		add(p_2);

		addCoupling(this, "in", p_1, "in");
		addCoupling(p_1, "out", p_2, "in");
		addCoupling(p_2, "out", this, "out");
		
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(463, 297);
        ((ViewableComponent)withName("p_2")).setPreferredLocation(new Point(104, 208));
        ((ViewableComponent)withName("p_1")).setPreferredLocation(new Point(99, 22));
    }
}
