package midterm;
import java.awt.*;
import simView.*;

public class efp extends ViewableDigraph 
{

	public efp()
	{
		super("efp");
		
		ViewableAtomic sg = new genr("genr", 30);
		ViewableDigraph  expf = new ef("ExpFrame", 10, 10);

		add(expf);
		add(sg);

		addCoupling(expf, "out", sg, "in");

		addCoupling(sg, "out", expf, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("ExpFrame")).setPreferredLocation(new Point(381, 160));
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(82, 451));
    }
 }
