package Lab10_practice1;
import java.awt.*;
import simView.*;

public class LRBSM extends ViewableDigraph
{
	final int NODE = 6;
	protected int [] proc_t = {0, 25, 15, 30, 50, 40, 25};
	protected int [] q_size = {0, 3, 5, 4, 3, 5, 3};
	
	public LRBSM()
	{
		super("LRBSM");
    	
		ViewableAtomic g = new genr("genr", 4);
		ViewableAtomic s = new scheduler("scheduler", 0, NODE, q_size);
		ViewableAtomic t = new transd("transd", 5000, NODE);
    	
		add(g);
		add(s);
		add(t);
  
		addCoupling(g, "out", s, "in");
		addCoupling(g, "out", t, "ariv");
		addCoupling(t, "out", g, "in");
		
		addCoupling(s, "out_loss", t, "loss");
		
		for(int i=1; i<=NODE; i++) {
			ViewableAtomic p = new processor("processor"+i, proc_t[i], q_size[i]);
			add(p);
			addCoupling(p, "out", s, "in"+i);
			addCoupling(p, "out", t, "solved");
			addCoupling(s, "out"+i, p, "in");
		}
	} 

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(-23, 94));
        ((ViewableComponent)withName("scheduler")).setPreferredLocation(new Point(155, 222));
        ((ViewableComponent)withName("processor4")).setPreferredLocation(new Point(419, 279));
        ((ViewableComponent)withName("processor1")).setPreferredLocation(new Point(417, 55));
        ((ViewableComponent)withName("transd")).setPreferredLocation(new Point(690, 244));
        ((ViewableComponent)withName("processor5")).setPreferredLocation(new Point(420, 352));
        ((ViewableComponent)withName("processor6")).setPreferredLocation(new Point(423, 431));
        ((ViewableComponent)withName("processor2")).setPreferredLocation(new Point(417, 125));
        ((ViewableComponent)withName("processor3")).setPreferredLocation(new Point(420, 206));
    }
}
